name: molgpt
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - rdkit
  - pytorch
  - pip:
      - guacamol
      - fcd-torch